ignore:
  # Ignore specific CVEs
  - vulnerability: CVE-2025-4517
  - vulnerability: CVE-2025-68121
  - vulnerability: GHSA-p77j-4mvh-x3m3
  - vulnerability: GHSA-vmwr-mc7x-5vc3
  - vulnerability: CVE-2025-4330
  - vulnerability: CVE-2025-4435
  - vulnerability: CVE-2025-4138
  - vulnerability: CVE-2025-8194
  - vulnerability: CVE-2025-13836
  - vulnerability: CVE-2024-9287
  - vulnerability: CVE-2025-61726
  - vulnerability: CVE-2026-4519
  - vulnerability: CVE-2026-25679
  - vulnerability: CVE-2025-61725
  - vulnerability: CVE-2025-61723
  - vulnerability: CVE-2025-61729
  - vulnerability: GHSA-4vrq-3vrq-g6gg
  - vulnerability: CVE-2025-58187
  - vulnerability: CVE-2026-27137
  - vulnerability: CVE-2025-47907
  - vulnerability: CVE-2025-61731 
  - vulnerability: GHSA-9h8m-3fm2-qjrq
  - vulnerability: CVE-2025-61732
  - vulnerability: GHSA-4c29-8rgm-jvjj
  - vulnerability: CVE-2025-58188
  - vulnerability: CVE-2025-4674
  - vulnerability: GHSA-x744-4wpc-v9h2
