FROM golang:1.26.1-bookworm
RUN apt-get update && apt-get install -y \
    jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY scripts/install_cosign.sh /tmp/install_cosign.sh
COPY scripts/install_trivy.sh /tmp/install_trivy.sh
RUN INSTALL_DIR=/usr/local/bin /tmp/install_cosign.sh
RUN INSTALL_DIR=trivy_arm64 ARCH=ARM64 /tmp/install_trivy.sh
RUN INSTALL_DIR=trivy_amd64 ARCH=64bit /tmp/install_trivy.sh
