FROM archlinux:latest AS build
ARG TARGETARCH
RUN pacman -Sy --noconfirm cosign bash curl jq
COPY scripts/install_trivy.sh /tmp/install_trivy.sh
RUN INSTALL_DIR=/tmp/trivy/ ARCH=64bit /tmp/install_trivy.sh

FROM scratch
COPY --from=build /tmp/trivy/trivy /
ENTRYPOINT ["/trivy"]
