FROM alpine:3.23.3 AS build
ARG TARGETARCH
ARG GRANT_VERSION="0.6.4"
ENV GRANT_VERSION=${GRANT_VERSION}
RUN apk add --no-cache cosign bash curl jq
COPY --chmod=755 scripts/install_anchore_tool.sh /tmp/install_anchore_tool.sh
RUN case "${TARGETARCH}" in \
        x86_64|amd64) ANCHORE_ARCH=amd64 ;; \
        aarch64|arm64) ANCHORE_ARCH=arm64 ;; \
        *) echo "Unsupported TARGETARCH: ${TARGETARCH}" && exit 1 ;; \
    esac \
   && INSTALL_DIR=/tmp/anchore/ TOOL=grant ARCH="${ANCHORE_ARCH}" VERSION="${GRANT_VERSION}" /tmp/install_anchore_tool.sh

FROM scratch
COPY --from=build /tmp/anchore/grant /grant
ENTRYPOINT ["/grant"]
