FROM golang:1.26.1-bookworm AS build
RUN apt-get update && apt-get install -y \
    jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY src/base/.devcontainer/scripts/install_cosign.sh /tmp/install_cosign.sh
COPY src/base/.devcontainer/scripts/install_trivy.sh /tmp/install_trivy.sh
RUN INSTALL_DIR=/usr/local/bin /tmp/install_cosign.sh
RUN INSTALL_DIR=/tmp/trivy/ ARCH=64bit /tmp/install_trivy.sh

FROM scratch
COPY --from=build /tmp/trivy/trivy /
ENTRYPOINT ["/trivy"]
