FROM serversideup/github-cli:2.89.0 AS build
ARG TARGETARCH
ARG TFLINT_VERSION="v0.61.0"
COPY --chmod=755 scripts/install_tflint.sh /tmp/install_tflint.sh
RUN --mount=type=secret,id=GH_TOKEN,env=GH_TOKEN \
    INSTALL_DIR=/tmp/tflint/ \
    ARCH="${TARGETARCH}" \
    VERSION="${TFLINT_VERSION}" \
    /tmp/install_tflint.sh

FROM scratch
COPY --from=build /tmp/tflint/tflint /tflint
ENTRYPOINT ["/tflint"]
