name: build_all_images
'on':
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
      tag_latest:
        required: true
        type: boolean
      NO_CACHE:
        required: true
        type: boolean
permissions: {}
jobs:
  discover_folders:
    runs-on: ubuntu-22.04
    outputs:
      base_node_folders: ${{ steps.find-folders.outputs.base_node }}
      node_24_language_folders: ${{ steps.find-folders.outputs.node_24_languages }}
      project_folders: ${{ steps.find-folders.outputs.projects }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - id: find-folders
        run: |
          base_node_folders=$(find src/base_node -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | jq -R -s -c 'split("\n")[:-1]')
          node_24_language_folders=$(find src/languages -mindepth 1 -maxdepth 1 -type d -name 'node_24*' -printf '%f\n' | jq -R -s -c 'split("\n")[:-1]')
          project_folders=$(find src/projects -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | jq -R -s -c 'split("\n")[:-1]')
          {
            echo "base_node=$base_node_folders"
            echo "node_24_languages=$node_24_language_folders"
            echo "projects=$project_folders"
          } >> "$GITHUB_OUTPUT"

  build_tool_images:
    # build common tool images with a lower scoped github token
    # as it uses a 3rd party docker image with github cli installed to verify attestation of binaries downloaded from github
    # and we don't want to make a high scoped token available to that image
    # token needs attestation read so it can verify attestation of binaries
    name: Build tool images for on ${{ matrix.arch }}
    runs-on: '${{ matrix.runner }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    permissions:
      contents: read
      attestations: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: build_tools
        run: |
          make build-tools
          docker save "local_grype:latest" -o grype_image.tar
          docker save "local_syft:latest" -o syft_image.tar
          docker save "local_grant:latest" -o grant_image.tar
          docker save "local_tflint:latest" -o tflint_image.tar
          docker save "local_zizmor:latest" -o zizmor_image.tar
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        name: Upload docker images
        with:
          name: docker_artifact_${{ matrix.arch }}
          path: |
            grype_image.tar
            syft_image.tar
            grant_image.tar
            tflint_image.tar
            zizmor_image.tar
  package_base_docker_image:
    uses: ./.github/workflows/build_multi_arch_image.yml
    permissions:
      attestations: write
      contents: read
      packages: write
      id-token: write
    needs: [build_tool_images]
    with:
      tag_latest: ${{ inputs.tag_latest }}
      docker_tag: ${{ inputs.docker_tag }}
      container_name: base
      base_folder: "."
      NO_CACHE: ${{ inputs.NO_CACHE }}
  package_base_node_images:
    needs:
      - package_base_docker_image
      - discover_folders
    permissions:
      attestations: write
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
            container_name: ${{ fromJson(needs.discover_folders.outputs.base_node_folders) }}
    uses: ./.github/workflows/build_multi_arch_image.yml
    with:
      tag_latest: ${{ inputs.tag_latest }}
      docker_tag: ${{ inputs.docker_tag }}
      container_name: ${{ matrix.container_name }}
      base_folder: "base_node"
      NO_CACHE: ${{ inputs.NO_CACHE }}
      EXTRA_COMMON: "common_node_24"
  package_node_24_language_docker_images:
    needs:
      - package_base_docker_image
      - package_base_node_images
      - discover_folders
    permissions:
      attestations: write
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
            container_name: ${{ fromJson(needs.discover_folders.outputs.node_24_language_folders) }}
    uses: ./.github/workflows/build_multi_arch_image.yml
    with:
      tag_latest: ${{ inputs.tag_latest }}
      docker_tag: ${{ inputs.docker_tag }}
      container_name: ${{ matrix.container_name }}
      base_folder: "languages"
      NO_CACHE: ${{ inputs.NO_CACHE }}
      EXTRA_COMMON: "common_node_24"
  package_project_docker_images:
    needs:
      - package_node_24_language_docker_images
      - discover_folders
    permissions:
      attestations: write
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        container_name: ${{ fromJson(needs.discover_folders.outputs.project_folders) }}
    uses: ./.github/workflows/build_multi_arch_image.yml
    with:
      tag_latest: ${{ inputs.tag_latest }}
      docker_tag: ${{ inputs.docker_tag }}
      container_name: ${{ matrix.container_name }}
      base_folder: "projects"
      NO_CACHE: ${{ inputs.NO_CACHE }}
      EXTRA_COMMON: "common_node_24"
