name: merge to main workflow
on:
  push:
    branches: [main]
permissions: {}

jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@c4efd04c5ff1c7e92e7fe5932b29d0de1a301cdf
    with:
      verify_published_from_main_image: true
    permissions:
      attestations: read
      contents: read
      packages: read
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@8b259f4f2d2b8ff1345fb0d2f9b9f0fbb9d19845
    needs:
      - get_config_values
    permissions:
      contents: read
      packages: read
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
    secrets:
      SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
  tag_release:
    needs: [quality_checks, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@c4efd04c5ff1c7e92e7fe5932b29d0de1a301cdf
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      dry_run: true
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}
  build_all_images:
    needs: 
      - tag_release
      - get_config_values
    uses: ./.github/workflows/build_all_images.yml 
    permissions:
      attestations: write
      contents: read
      packages: write
      id-token: write
    with: 
      docker_tag: 'ci-${{ needs.tag_release.outputs.version_tag }}'
      tag_latest: false
      NO_CACHE: false
